### ISSUE TITLE
Use filters in query solr.LowerCaseFilterFactory

### ISSUE THREAD

**Issue by royopa** [floriansemm/SolrBundle#106]
How I add the filter to use search in lowercase?

Example:

```php
$querySolr = $this->get('solr.client')->createQuery('AppBundle:Demanda');
$value = 'Coalto';
$query->addSearchTerm('description', $value);
```

So, my search would be returns searches: "coalto" and "Coalto".

Maybe interesting add the how to code in README.

**Comment by floriansemm** [comment]
All query classes extend `Solarium\QueryType\Select\Query\Query`

So you can do the following: 

```php
$query = $this->get('solr')->createQuery('AppBundle:Demanda');
$query->createFilterQuery()->setQuery('....')
```

For more information have a look at the [Solarium docu](http://wiki.solarium-project.org/index.php/V3:Adding_filterqueries)

**Comment by royopa** [comment]
The problem is in my result search is case sensitive, but I dont get make this:

If I have a field with value "MY Title" the query is not return result.

``php
$query = $this->get('solr.client')->createQuery('AcmeDemoBundle:Post');
$query->queryAllFields('my title');

$result = $query->getResult();
``

**Comment by floriansemm** [comment]
Your problem is Solr specific. I think [this](http://stackoverflow.com/questions/8240329/solr-case-insensitive-search) stack-overflow article could solve problem.
