### ISSUE TITLE
All fields are returned

### ISSUE THREAD

**Issue by wassafr** [floriansemm/SolrBundle#116]
I've followed the example of the README to have only one field to be mapped : 

$search = $request->get('search_query');

$query = $this->get('solr.client')->createQuery('WassaIndoorWayfindingAdminBundle:Poi');
$query->addSearchTerm('name', $search);
$query->setHydrationMode(HydrationModes::HYDRATE_INDEX);
$query->addField('id');
$pois = $query->getResult();

foreach ($pois as $poi) {
    echo $poi->getMapId();   // Display the real value whilst the doc says it should be empty
}

**Comment by floriansemm** [comment]
this was an bug in solr. should be fixed.

**Comment by wassafr** [comment]
I think your fix broke something. With the exact same code I don't get any result anymore, $pois is always empty.

**Comment by floriansemm** [comment]
What is the result when you run the query without `addField`?

**Comment by wassafr** [comment]
Same result, it doesn’t return anything.

De : Florian Semm <notifications@github.com<mailto:notifications@github.com>>
Répondre à : floriansemm/SolrBundle <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : dimanche 21 février 2016 16:11
À : floriansemm/SolrBundle <SolrBundle@noreply.github.com<mailto:SolrBundle@noreply.github.com>>
Cc : John WALTER <john.walter@wassa.fr<mailto:john.walter@wassa.fr>>
Objet : Re: [SolrBundle] All fields are returned (#116)


What is the result when you run the query without addField?

**Comment by floriansemm** [comment]
Please add `$query->setUseWildcard(false);` and run the query again.

For extra debugging information start `tail -f app/logs/dev.log | grep solr`. You can see something like `solr.INFO: run request: select?omitHeader=true&wt=json&json.nl=flat&q=title_s:"relation 1"&start=0&rows=10&fl=id [] []` (in your case something like name_s:"foo" instead of title_s)

Run the query in your solr-admin to make sure that your index contains data.

**Comment by wassafr** [comment]
Working now!

Thanks

**Comment by floriansemm** [comment]
Which version do you use?

**Comment by wassafr** [comment]
I use the latest version 1.3.2.
In the commit you talk about, you added the double quotes. That's precisely my problem because if I remove them from your code, it's working perfectly.

Finally, not using wildcard is not an option for me because I need have results that only match substrings of the fields.

**Comment by floriansemm** [comment]
@wassafr Is the problem still existent?
