### ISSUE TITLE
no declaration for document found in entity

### ISSUE THREAD

**Issue by bertrandom** [floriansemm/SolrBundle#12]
I'm getting this error: 

no declaration for document found in entity 

throw from MetaInformationFactory:

```
    if (!$this->annotationReader->hasDocumentDeclaration($entity)) {
        throw new \RuntimeException(sprintf('no declaration for document found in entity %s', $className));
    }
```

when persisting an entity that I do not have a @Solr\Document annotation for. Is this expected? How do I exempt entities from being in Solr?

**Comment by piepkrak** [comment]
Hi,
We are using version 1.7.0.
After persisting and flushing an entity with Docrine this Exception is still thrown for entities that do not need to be indexed.
Doesn't the postFlush method on Doctrine\ORM\Listener\EntityIndexerSubscriber need a try-catch like the postUpdate method?

**Comment by gadelkareem** [comment]
I am getting this error as well "floriansemm/solr-bundle": "^1.7.1",
