### ISSUE TITLE
"unkown field" - Best way to create the document schema in solr

### ISSUE THREAD

**Issue by ozzmaster** [floriansemm/SolrBundle#129]
Hi everyone

I would like to know if there is a way for my Symfony app, using this bundle, to create the initial schema of the solr documents automatically?

Should I code in an event listener or something that will connect to solr, check if an entity's document schema exists solr and if not create it?

Apologies if my terminology is not correct. I have been using ElasticSearch in other project and the bundle I use there creates everything that is needed when the index is recreated.

**Comment by floriansemm** [comment]
Your solr-instance already contains a schema.xml in the `example-DIH` folder.
