### ISSUE TITLE
\DateTime properties cannot be indexed

### ISSUE THREAD

**Issue by Martin1982** [floriansemm/SolrBundle#134]
When running solr:index:populate on an entity with this field;

```
/**
 * @var \DateTime
 *
 * @Solr\Field(type="date")
 */
protected $publicationDateStart;
```

The following error occurs:

`A error occurs: no declaration for document found in entity DateTime`

**Comment by Martin1982** [comment]
I just noticed this is solved in issue #123 but having it in the README.md would help not to fall for it again ;)

**Comment by Martin1982** [comment]
While working on my index I came across another error from Solr complaining about the date format. In the end this was the solution that worked for me;

     * @Solr\Field(type="datetime", getter="format('Y-m-d\TH:i:s\Z')")

**Comment by floriansemm** [comment]
Thanks good point. Documentation is now update to date.
