### ISSUE TITLE
sorl configuration issue in localhost

### ISSUE THREAD

**Issue by akshar0478** [floriansemm/SolrBundle#138]
Hi,

I am new in solr.  i have installed solr in localhost and configure solrbundle as well but when i trying to 
serach data from my controller action it was give me result blank. I dont know where is missing configuration. 

I have created core in solr. and add that core detail in config.yml in symfony project. I am using windows xampp.
# solr bundle

fs_solr:
    endpoints:
        jobscroller:
            host: localhost
            port: 8983
            path: C:\Bitnami\solr-6.2.1-2\apache-solr\server\solr\jobscroller
            timeout: 5
            core: jobscroller

Any one know  how to fix it?

**Comment by Koalabaerchen** [comment]
Did you populate solr? 
If you go onto solr with the solr admin, select your core and do a query, does it give you something back?
(link should be something like http://localhost:8983/solr/#/jobscroller/query)

Did you tell solr what fields of your entity to put into solr? (php app/console solr:index:populate should give you some hints about that)

**Comment by floriansemm** [comment]
ping @akshar0478
