### ISSUE TITLE
Composer Update (or Require) fails due to minimum-stability

### ISSUE THREAD

**Issue by Koalabaerchen** [floriansemm/SolrBundle#140]
```
{
    ...
    "require": {
        ...
       "floriansemm/solr-bundle":                  "^1.6",
       ...
    }
}
```

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Removal request for minimalcode/search == 1.0.0.0-RC1
    - floriansemm/solr-bundle v1.6 requires minimalcode/search ^1.0 -> satisfiable by minimalcode/search[1.0.0-RC1].
    - Installation request for floriansemm/solr-bundle ^1.6 -> satisfiable by floriansemm/solr-bundle[v1.6].
```

It happens because of no set "minimum-stability".

Adding a `"minimum-stability": "RC",` fixes that problem.

**Comment by floriansemm** [comment]
the composer.json file contains a `"minimum-stability": "beta",`, so you must add `"minimum-stability": "RC"` in your project

**Comment by Koalabaerchen** [comment]
I think the install documentation should include that.

Default Symfony composer.json comes without minimum-stability (which defaults to stable) I believe.

**Comment by floriansemm** [comment]
`"minimum-stability": "beta"` is temporarily as long as a final release was published
