### ISSUE TITLE
Multiple core set unique index populate

### ISSUE THREAD

**Issue by ViceDigitWeb** [floriansemm/SolrBundle#143]
Hi, 
In my project I have two core for solr.
When my webservice inject data, my two core are well indexed.

But for exemple if I need to populate himself with solr:index:populate. This command create only one index in first core.

Have you an idea how I can resolve this situation.

Best regards,

Vincent.

**Comment by floriansemm** [comment]
try this: https://github.com/floriansemm/SolrBundle#indexhandler-property

**Comment by ViceDigitWeb** [comment]
Not working for me, work when i insert from symfony data, index it's ok, but i have this problem only if i use console/shell for launch command solr:index:populate.

**Comment by floriansemm** [comment]
Your problem should be fixed in 	9f8e5bf

If no `@Solr\Document(index="..")` or `@Solr\Document(indexHandler="..")` is set then the first core-config from your config.yml is used

**Comment by ViceDigitWeb** [comment]
Ok thanks a lot, i can't test now because stability requirement. But great job :)

**Comment by ViceDigitWeb** [comment]
I have change my stability requirement, it's work perfect, just one detail, the field id have the same prefix document name. But it's a detail , my two core is populate correctly. So I close this open issue because it's done in the first request.
