### ISSUE TITLE
ManyToOne Relation doesn't create Entity Object out of Solr result

### ISSUE THREAD

**Issue by Koalabaerchen** [floriansemm/SolrBundle#149]
Between Release 1.6.1 and 1.6.2 something broke with ManyToOne relations. It's also still broken in dev-master (as of writing).

My Job() entity
```
/**
* @var AcmeBundle\Entity\Company
*
* @ORM\ManyToOne(targetEntity="AcmeBundle\Entity\Company", inversedBy="jobs")
* @ORM\JoinColumn(name="company_id", referencedColumnName="id", onDelete="SET NULL")
* @Solr\Field(type="string", getter="getTitle")
*/
private $company;
```

My query:
```
$query = $this->get('solr.client')->createQuery(new Job());
$query->setHydrationMode(HydrationModes::HYDRATE_INDEX);
$results = $query->getResult();
```

With a version > 1.6.1 my tests fail with the following error:

> [2016-11-28 13:35:31] solr.ERROR: the error "Argument 1 passed to AcmeBundle\Entity\Job::setCompany() must be an instance of AcmeBundle\Entity\Company, string given, called in \vendor\floriansemm\solr-bundle\FS\SolrBundle\Doctrine\Hydration\PropertyAccessor\MethodCallPropertyAccessor.php on line 25 and defined" occure while executing event query solr [] []

Now I'm wondering if something changed (that isn't reflected inside the documentation) or the entitymapper (?) broke or I'm totally wrong on my end and it just happened to work before.
It tries to parse the string directly out of solr into the setCompany method, not the actual Company object (which it doesn't get).

**Comment by floriansemm** [comment]
the way how the data is mapped changed a bit. In previous releases the mapper accesses directly a class-property and sets the data, which is expensive. Now the mapper calls the setter-function of the given property.

To fix your problem just remove the type-hint in your setter-method.

**Comment by Koalabaerchen** [comment]
OK, performance is a reason I understand, at least. And thanks for pointing in the direction of the code.

I'll have to test it. If I remember correctly it broke even after I removed the hint. Will come back to you.

**Comment by Koalabaerchen** [comment]
Finally got around to testing that.

Removing the type hint solves the problem. I need to monitor it because I usually relied on that type hint for the sake of doctrine, but I guess I don't really need it.

Thanks and closing!

**Comment by floriansemm** [comment]
No problem!
