### ISSUE TITLE
Index discriminator columns,  support for virtual attributes/fields .. 

### ISSUE THREAD

**Issue by jadelrab** [floriansemm/SolrBundle#158]
Hello, 

Is there a way to add discriminator columns into schema index ? I've tried to add it as a virtual attribute (without @ ORM\Column annotation) but with "getter" set to a public method and it not working although it shows in solr:schema:show command as "_document_type_s" .. 

```
     /**
     * @Solr\Field(type="string", name="type", getter="getDocumentType")
     *
     * @var String
     */
    private $documentType;
```

I checked the closed pull request and found an implementation for virtual fields by @zquintana  but it seems missed in master branch 

Thanks

**Comment by Koalabaerchen** [comment]
> This bundle is designed for Doctrine Entities. Other datasources are not supported, but you can implement your own stuff and use the underlying Solarium Lib to index documents.

[Source](https://github.com/floriansemm/SolrBundle/issues/157#issuecomment-276975328)

**Comment by jadelrab** [comment]
Hi @Koalabaerchen , 

Thanks for the info, but regarding the discriminator field it is totally a Doctrine entity related, anyway, I've found a simple way to put the attribute with its value in the entity class itself, 

Thanks,

**Comment by zquintana** [comment]
@jadelrab if you are looking for this feature, I've forked this project and added some additional goodies for a recent project that had additional requirements. https://github.com/zquintana/SunSearchBundle.
