### ISSUE TITLE
Control what trigger a delete from the index

### ISSUE THREAD

**Issue by Mortagus** [floriansemm/SolrBundle#160]
Hello,

If I understood correctly how the bundle works, when a delete request is made to a specific data (like delete by it's primary key), SolrBundle remove that information from the index.

First question: is that correct ?

That said, my real question is : how can I trigger a delete from the solr index ? I would like to apply specific condition and I didn't find how to do it.

**Comment by floriansemm** [comment]
A doctrine-listener listens on `preRemove` events, which are trigger after calling `$em->remove($entity)`;

To delete a document execute `$solr->removeDocument($entity)`

**Comment by Mortagus** [comment]
Cool thanks. 

So simple, I'm face-palming myself right now ^^.

But did I miss the information into the documentation ? If so, can you show me where it is please ?

**Comment by floriansemm** [comment]
No problem!

this part of the api is not documented, sry.
