### ISSUE TITLE
symfony 4 - error

### ISSUE THREAD

**Issue by hanzx** [floriansemm/SolrBundle#174]
hi,

php bin/console cache:clear --env=dev --no-warmup

`PHP Fatal error:  Class FS\SolrBundle\DataCollector\RequestCollector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::reset) in /var/www/artikul/website/vendor/floriansemm/solr-bundle/FS/SolrBundle/DataCollector/RequestCollector.php on line 100
PHP Stack trace:
PHP   1. {main}() /var/www/artikul/website/bin/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /var/www/artikul/website/bin/console:36
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/artikul/website/vendor/symfony/console/Application.php:143
PHP   4. App\Kernel->boot() /var/www/artikul/website/vendor/symfony/framework-bundle/Console/Application.php:64
PHP   5. App\Kernel->initializeContainer() /var/www/artikul/website/vendor/symfony/http-kernel/Kernel.php:125
PHP   6. Symfony\Component\DependencyInjection\ContainerBuilder->compile() /var/www/artikul/website/vendor/symfony/http-kernel/Kernel.php:513
PHP   7. Symfony\Component\DependencyInjection\Compiler\Compiler->compile() /var/www/artikul/website/vendor/symfony/dependency-injection/ContainerBuilder.php:711
PHP   8. Symfony\Component\DependencyInjection\Compiler\AutowirePass->process() /var/www/artikul/website/vendor/symfony/dependency-injection/Compiler/Compiler.php:95
PHP   9. Symfony\Component\DependencyInjection\Compiler\AutowirePass->process() /var/www/artikul/website/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:47
PHP  10. Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue() /var/www/artikul/website/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:39
PHP  11. Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue() /var/www/artikul/website/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:61
PHP  12. Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue() /var/www/artikul/website/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:81
PHP  13. Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue() /var/www/artikul/website/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:60
PHP  14. Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue() /var/www/artikul/website/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:61
PHP  15. Symfony\Component\DependencyInjection\Compiler\AutowirePass->autowireCalls() /var/www/artikul/website/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:104
PHP  16. Symfony\Component\DependencyInjection\Compiler\AutowirePass->autowireMethod() /var/www/artikul/website/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:138
PHP  17. Symfony\Component\DependencyInjection\Compiler\AutowirePass->getAutowiredReference() /var/www/artikul/website/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:193
PHP  18. Symfony\Component\DependencyInjection\Compiler\AutowirePass->populateAvailableTypes() /var/www/artikul/website/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:241
PHP  19. Symfony\Component\DependencyInjection\Compiler\AutowirePass->populateAvailableType() /var/www/artikul/website/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:261
PHP  20. Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass() /var/www/artikul/website/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:275
PHP  21. Symfony\Component\Config\Resource\ClassExistenceResource->isFresh() /var/www/artikul/website/vendor/symfony/dependency-injection/ContainerBuilder.php:331
PHP  22. class_exists() /var/www/artikul/website/vendor/symfony/config/Resource/ClassExistenceResource.php:76
PHP  23. spl_autoload_call() /var/www/artikul/website/vendor/symfony/config/Resource/ClassExistenceResource.php:76
PHP  24. Symfony\Component\Debug\DebugClassLoader->loadClass() /var/www/artikul/website/vendor/symfony/config/Resource/ClassExistenceResource.php:76

In RequestCollector.php line 100:
                                                                               
  Error: Class FS\SolrBundle\DataCollector\RequestCollector contains 1 abstra  
  ct method and must therefore be declared abstract or implement the remainin  
  g methods (Symfony\Component\HttpKernel\DataCollector\DataCollectorInterfac  
  e::reset)    `

**Comment by floriansemm** [comment]
see #175
