### ISSUE TITLE
Get specific fields

### ISSUE THREAD

**Issue by dev-yann** [floriansemm/SolrBundle#180]
Can i have a query example for get a specific fields ? I try this but it doesn't work 
```php
$query = $client->createQuery('Wim\Api\Document\Objet');
$query->addField('id');
 $query->createFilterQuery('bounds')->setQuery('location.geo:[' . $bounds1 . ',' . $bounds2 . ' TO ' . $bounds3 . ',' . $bounds4 . ']');
$query->getResult();
````
This code should give me only 'id' list, no ? ( I have all fields in result )

**Comment by floriansemm** [comment]
`$query->getResult()` will return a array of mapped objects and not a list of fields

**Comment by dev-yann** [comment]
Okai but do you know how can i get two or more specific fields ? If I want Id, name and surname for example ?

**Comment by floriansemm** [comment]
you can use Solarium API for that. Call the `solr.client.adapter` service to get the solarium-client.
