### ISSUE TITLE
[Feature Request] Relations

### ISSUE THREAD

**Issue by rafalzmuda** [floriansemm/SolrBundle#2]
Can You answer this question asked by Christian here http://knpbundles.com/floriansemm/SolrBundle?

"I'd like to know if it works with relationships between entities. For example, if your Post entity had an $author property of the class Author and I wish to index some of the author's information along with the post's. Is it possible?

An example with a many to many relationship would be if the Posts had a $tags property consisting of an array of Tag entities, is it possible to map this with annotations?"

thx

**Comment by thorbenheins** [comment]
Is this working now?

**Comment by floriansemm** [comment]
no

**Comment by thorbenheins** [comment]
Too Bad. THX for the great bundle anyways!

On Jan 14, 2015, Florian Semm <notifications@github.com> wrote:
>no
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/floriansemm/SolrBundle/issues/2#issuecomment-69878637

--
Sent from my "smart"-phone, please disregard the typos!

**Comment by weburnit** [comment]
@floriansemm I am intending to extend some features for this project! ;)

**Comment by floriansemm** [comment]
@weburnit sound great!
