### ISSUE TITLE
Solr::updateDocument and Solr::addToIndex

### ISSUE THREAD

**Issue by mathewrapid** [floriansemm/SolrBundle#91]
Should the updateDocument also check if the document should be added to index?

**Comment by floriansemm** [comment]
You mean if no changes happened to document/entity, do not call solr?

**Comment by mathewrapid** [comment]
e.g. usage with the Doctrine event listeners.

1. Have an entity `Foo` with `@Solr\SynchronizationFilter(callback="shouldBeIndex")`
2. Have this entity return `false` from said callback (`Foo::shouldBeIndex`)
3. Add entity do db -> call to `AddDocumentListener::postPersist` -> `Solr::addDocument`
4. `Solr::addToIndex` checks if the entity should be added or not with `Solr::addToIndex`. The entity should not be added to index because point of 2.
5. Modify the entity and persist the changes -> call to `UpdateDocumentListener::postUpdate` -> `Solr::updateDocument`. Remember `Foo::shouldBeIndex` returns `false`
6. **is a document added to solr or not?**

ps. I haven't used this bundle yet. This question only from reading the docs and source.

**Comment by floriansemm** [comment]
The method `updateDocument` performs a check: https://github.com/floriansemm/SolrBundle/blob/master/Solr.php#L199

Internally `addToIndex` returns the return-value of the `@Solr\SynchronizationFilter` callback. See https://github.com/floriansemm/SolrBundle/blob/master/Solr.php#L232

**Comment by mathewrapid** [comment]
> The method updateDocument performs a check: https://github.com/floriansemm/SolrBundle/blob/master/Solr.php#L199

That is the `addDocument` method, not the `updateDocument` method.
Am I missing something here?

See https://github.com/floriansemm/SolrBundle/blob/master/Solr.php#L195-211 vs https://github.com/floriansemm/SolrBundle/blob/master/Solr.php#L316-330

**Comment by floriansemm** [comment]
Your are right!

`updateDocument` should also use `addToIndex`.
