### ISSUE TITLE
The synch command always send Synchronized Documents: 0

### ISSUE THREAD

**Issue by jeremygachet** [floriansemm/SolrBundle#96]
Hello and thank you for your bundle, 
I'im trying to use it but I cannot solve may issue, when I launch the sync commande its returns: 
Synchronization successful

Synchronized Documents: 0
Not Synchronized Documents: 0

Overall: 0

I try with 3 different entities, but nothing works and I can't figure why.

Below is my config: 
fs_solr:
  endpoints:
    core0:
      host: myslor.dev
      port: 8983
      path: /solr/project
      timeout: 10

My entity: 

use FS\SolrBundle\Doctrine\Annotation as Solr;

/**
 * Article.
 *
 * @Solr\Document(repository="ContentBundle\Entity\Article")
 * 
 * @ORM\Table(name="article", indexes={@ORM\Index(name="slug_idx", columns={"slug"} )})
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 * @ORM\Entity(repositoryClass="ContentBundle\Repository\ArticleRepository")
 */
class Article
{
    const PUBLISH = 'publié';

    /**
     * @var int
     * @Solr\Id
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @Solr\Field(type="string")
     * @var string
     * @ORM\Column(name="toptitle", type="string", length=255)
     */
    private $toptitle;

    /**
     * @Solr\Field(type="string")
     * @var string
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

....
}

I'm on a Solr 3.6.

Thank you in advance for your help

**Comment by floriansemm** [comment]
@jeremygachet it was just an display-bug. The master contains the fix.
