### ISSUE TITLE
probleme with service in last update

### ISSUE THREAD

**Issue by jeremygachet** [floriansemm/SolrBundle#98]
Hello, 
I've got an issue with the last update of the bundle.
Theire are spaces around the definition of the service :  

                                                                                                              
              FS\\SolrBundle\\Doctrine\\ClassnameResolver\\KnownNamespaceAliases                                   
          
And it causes a break with the clear cache :
 [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                                       
  "'                                                                                                               
              FS\\SolrBundle\\Doctrine\\ClassnameResolver\\KnownNamespaceAliases                                   
          '" is not a valid class name for the "solr.doctrine.classnameresolver.known_entity_namespaces" service.

**Comment by floriansemm** [comment]
@jeremygachet is was an formatting issue in the configuration xml. It should be fixed.

**Comment by jeremygachet** [comment]
Yes it's a very small bug ;)
